//
//  SchoolSearchWorkerTests.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/15/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NYC_Youths
import XCTest

class SchoolSearchWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SchoolSearchWorker!
    var delegateTest: SchoolSearchWorkerDelegateTest!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        delegateTest = SchoolSearchWorkerDelegateTest()
        sut = SchoolSearchWorker(delegate: delegateTest)
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    // MARK: Test doubles
    
    struct SchoolSearchWorkerDelegateTest: SchoolSearchWorkerDelegate {
        func handleSchoolData(_ data: [SchoolData]) {
            XCTAssert(data.count > 0)
        }
        
        func handleError(_ error: Error) {
            XCTAssertNotNil(error)
        }
    }
    
    // MARK: Tests
    
    func testGetSchoolsFromSource()
    {
        let schools = sut.getSchoolData()
        XCTAssertEqual([[:]], schools)
    }
    
    func testErrorFromSchoolDataSource() {
        let error = sut.getSchoolData()
        XCTAssertEqual("API Failure", error)
    }
    
    fu
}//end SchoolSearchWorkerTests
