//
//  SchoolSearchWorkerTests.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/15/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NYC_Youths
import XCTest

class SchoolSearchWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: SchoolSearchWorker!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupSchoolSearchWorker()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSchoolSearchWorker()
    {
        sut = SchoolSearchWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testGetSchoolsFromSource()
    {
        let schools = sut.getSchoolData()
        XCTAssertEqual([[:]], schools)
    }
    
    func testErrorFromSchoolDataSource() {
        let error = sut.getSchoolData()
        XCTAssertEqual("API Failure", error)
    }
    
    fu
}//end SchoolSearchWorkerTests
