//
//  SchoolSearchInteractor.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/15/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


protocol SchoolSearchBusinessLogic
{
    func performStartingActions()
}

protocol SchoolSearchDataStore
{
    var schools: [School]! {get}
}

class SchoolSearchInteractor: SchoolSearchBusinessLogic, SchoolSearchDataStore, SchoolSearchWorkerDelegate
{
    var schools: [School]!
    
    var presenter: SchoolSearchPresentationLogic?
    var worker: SchoolSearchWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func performStartingActions()
    {
        worker = SchoolSearchWorker(delegate: self)
        worker?.getData()
    }
    
    // MARK: Worker Delegate Functions
    
    func handleSchoolData(_ data: [SchoolData]) {
        print(data)
    }
    
    func handleError(_ error: Error) {
        print(error)
    }
}
