//
//  SchoolSearchViewController.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/15/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SchoolSearchDisplayLogic: AnyObject
{
    func displaySchoolList(data: [SchoolData])
    
    func displaySchoolDetails(_ school: SchoolData)
}

class SchoolSearchViewController: UIViewController, SchoolSearchDisplayLogic
{
    @IBOutlet weak var searchBar: UISearchBar!
    
    @IBOutlet weak var schoolListTableView: UITableView!
    
    var interactor: SchoolSearchBusinessLogic?
    var router: (NSObjectProtocol & SchoolSearchRoutingLogic & SchoolSearchDataPassing)?
    
    var listData: [SchoolData] = []
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SchoolSearchInteractor()
        let presenter = SchoolSearchPresenter()
        let router = SchoolSearchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        self.searchBar.delegate = self
        self.schoolListTableView.delegate = self
        self.schoolListTableView.dataSource = self
        interactor?.performStartingActions()
        
        self.hideKeyboard()
    }
    
    // MARK: Display Logic
    
    func displaySchoolList(data: [SchoolData]) {
        listData = data
        schoolListTableView.reloadData()
    }
    
    func displaySchoolDetails(_ school: SchoolData) {
        router?.routeToSchoolDetails(segue: nil, schoolData: school)
    }
    
}

// MARK: TableView Logic

extension SchoolSearchViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listData.count
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 75.0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let tableCell = UITableViewCell()
        var defaultContent = tableCell.defaultContentConfiguration()
        defaultContent.text = listData[indexPath.row].schoolName
        
        tableCell.contentConfiguration = defaultContent
        
        return tableCell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let school = listData[indexPath.row]
        self.interactor?.performSchoolDetailsAcquisition(name: school.schoolName)
    }
}

// MARK: SearchBar Logic

extension SchoolSearchViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        interactor?.performSchoolSearch(text: searchText)
    }
}

// MARK: Cell Configuration

