//
//  SchoolSearchPresenter.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/15/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol SchoolSearchPresentationLogic
{
    func presentSchoolData(data: [SchoolData])
    
    func presentSchoolDetails(school: SchoolData)
}

class SchoolSearchPresenter: SchoolSearchPresentationLogic
{
    weak var viewController: SchoolSearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSchoolData(data: [SchoolData])
    {
        DispatchQueue.main.async {
            self.viewController?.displaySchoolList(data: data)
        }
    }
    
    func presentSchoolDetails(school: SchoolData) {
        viewController?.displaySchoolDetails(school)
    }
}
