//
//  SchoolSearchModels.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/15/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


/// Network model for getting School data
struct School: Codable {
    let dbn, boro, neighborhood, location: String?
    let schoolName, overviewParagraph: String?
    let school10thSeats: String?
    let ellPrograms, languageClasses, advancedPlacementCourses, diplomaEndorsements: String?
    let sharedSpace, campusName, phoneNumber, faxNumber, buildingCode: String?
    
    
    enum CodingKeys: String, CodingKey {
        case dbn, boro, neighborhood, location
        case schoolName = "school_name"
        case overviewParagraph = "overview_paragraph"
        case school10thSeats = "school_10th_seats"
        case ellPrograms = "ell_programs"
        case languageClasses = "language_classes"
        case advancedPlacementCourses = "advancedplacement_courses"
        case diplomaEndorsements = "diplomaendorsements"
        case campusName = "campus_name"
        case sharedSpace = "shared_space"
        case buildingCode = "building_code"
        case phoneNumber = "phone_number"
        case faxNumber = "fax_number"
    }
}


/// Network Model for getting SAT Score data
struct SATScores: Codable {
    let dbn, schoolName, numberOfParticipants, criticalReadingAvg, mathAvg, writingAvg: String?
    
    enum CodingKeys: String, CodingKey {
        case dbn
        case schoolName = "school_name"
        case numberOfParticipants = "num_of_sat_test_takers"
        case criticalReadingAvg = "sat_critical_reading_avg_score"
        case mathAvg = "sat_math_avg_score"
        case writingAvg = "sat_writing_avg_score"
    }
}


/// This is the in app model we will use for the School and any relavent data
struct SchoolData {
    let dbn, boro, neighborhood, location: String
    let schoolName, overviewParagraph: String
    let numberOfSATParticipants, criticalReadingAvg, mathAvg, writingAvg: String
    
    init(school: School, satScores: SATScores) {
        self.dbn = school.dbn ?? ""
        self.schoolName = school.schoolName ?? ""
        self.overviewParagraph = school.overviewParagraph ?? ""
        self.boro = school.boro ?? ""
        self.neighborhood = school.neighborhood ?? ""
        self.location = school.location ?? ""
        self.numberOfSATParticipants = satScores.numberOfParticipants ?? ""
        self.criticalReadingAvg = satScores.criticalReadingAvg ?? ""
        self.mathAvg = satScores.mathAvg ?? ""
        self.writingAvg = satScores.writingAvg ?? ""
    }

}

