//
//  SchoolDetailsPresenter.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/17/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SchoolDetailsPresentationLogic
{
  func presentSomething(response: SchoolDetails.Something.Response)
}

class SchoolDetailsPresenter: SchoolDetailsPresentationLogic
{
  weak var viewController: SchoolDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SchoolDetails.Something.Response)
  {
    let viewModel = SchoolDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
