//
//  SchoolDetailsWorker.swift
//  NYC Youths
//
//  Created by Kartikeya Kaushal on 3/17/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SchoolDetailsWorker
{
  func doSomeWork()
  {
  }
}
